typography_spectrum: 0.7712067
color:
  saturation: 1
  brandStrength: 0.4880525
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#86B9EE'
    - '#6D9FD1'
    - '#5580AB'
    - '#2B4D86'
  rhythmicContrast: 1
layout_spectrum: 0.7317801
name: 'Assessment Services, Inc.'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Assessment Services, Inc.'
description: '"helping students and teachers excel"'
